# Initiliation

In [1]:
!pip install transformers datasets --quiet

     |████████████████████████████████| 3.4 MB 8.4 MB/s 
     |████████████████████████████████| 306 kB 50.4 MB/s 
     |████████████████████████████████| 3.3 MB 66.8 MB/s 
     |████████████████████████████████| 61 kB 483 kB/s 
     |████████████████████████████████| 895 kB 61.3 MB/s 
     |████████████████████████████████| 596 kB 59.4 MB/s 
     |████████████████████████████████| 1.1 MB 51.9 MB/s 
     |████████████████████████████████| 132 kB 67.8 MB/s 
     |████████████████████████████████| 243 kB 76.1 MB/s 
     |████████████████████████████████| 271 kB 55.5 MB/s 
     |████████████████████████████████| 192 kB 61.3 MB/s 
     |████████████████████████████████| 160 kB 50.3 MB/s 


In [2]:
from transformers import TrainingArguments
from transformers import Trainer
from transformers import AutoModelForSequenceClassification
from transformers import AutoTokenizer

from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support, accuracy_score, classification_report, confusion_matrix
from datasets import Dataset
from datasets import load_metric

import numpy as np
import math
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive

# Data Preparation

In [3]:
drive.mount('/content/drive/')

Mounted at /content/drive/


In [4]:
%cd 'drive/MyDrive/Masterarbeit/Colab Notebooks/OVERVIEW myPers/00_Datasets/URL'

/content/drive/.shortcut-targets-by-id/1aHXlqhpj1STohhfU4gn53D4whaLH__Jz/Masterarbeit/Colab Notebooks/OVERVIEW myPers/00_Datasets/URL


In [5]:
dfPJ = pd.read_csv('myPers_AGR_URL.csv', sep=",", error_bad_lines=False)
dfPJ

text  label
0                       likes  the  sound  of  thunder       0
1     is  so  sleepy  its  not  even  funny  thats  ...      0
2     is  sore  and  wants  the  knot  of  muscles  ...      0
3     likes  how  the  day  sounds  in  this  new  s...      0
4                                          is  home  3       0
...                                                 ...    ...
9912                   little  things  give  you  away       1
9913                    is  wishing  it  was  saturday       1
9914                 is  studying  hard  for  the  gre       1
9915                          snipers  get  more  head       0
9916  last  night  was  amazing  not  only  did  i  ...      0

[9917 rows x 2 columns]

In [6]:
df_clean= []
for i,row in dfPJ.iterrows():
  df_clean.append({
      'text': str(row['text']),
      'label': int(row['label']),
  })

dfPJ = pd.DataFrame(df_clean)
dfPJ

text  label
0                       likes  the  sound  of  thunder       0
1     is  so  sleepy  its  not  even  funny  thats  ...      0
2     is  sore  and  wants  the  knot  of  muscles  ...      0
3     likes  how  the  day  sounds  in  this  new  s...      0
4                                          is  home  3       0
...                                                 ...    ...
9912                   little  things  give  you  away       1
9913                    is  wishing  it  was  saturday       1
9914                 is  studying  hard  for  the  gre       1
9915                          snipers  get  more  head       0
9916  last  night  was  amazing  not  only  did  i  ...      0

[9917 rows x 2 columns]

# Model Training

In [7]:
modeltype = "princeton-nlp/sup-simcse-bert-base-uncased"

In [8]:
train, test = train_test_split(dfPJ, test_size=0.2, random_state=0, stratify=dfPJ.label)

train = Dataset.from_pandas(train)
test = Dataset.from_pandas(test)

tokenizer = AutoTokenizer.from_pretrained(modeltype)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_train = train.map(tokenize_function, batched=True)
tokenized_test = test.map(tokenize_function, batched=True)

full_train_dataset = tokenized_train
full_eval_dataset = tokenized_test

model = AutoModelForSequenceClassification.from_pretrained(modeltype, num_labels=2)

training_args = TrainingArguments(
    "SIMCSE_BERT_AGR", 
    evaluation_strategy="epoch",
    save_strategy = 'no',
    save_steps = 100000,
    save_total_limit = 1,
    metric_for_best_model="eval_f1")

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='macro')
    acc = accuracy_score(labels, preds)
    print(classification_report(labels, preds, labels=[0,1]))
    print(confusion_matrix(labels,preds))
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

Downloading:   0%|          | 0.00/252 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/689 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

  0%|          | 0/8 [00:00<?, ?ba/s]

  0%|          | 0/2 [00:00<?, ?ba/s]

Downloading:   0%|          | 0.00/418M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at princeton-nlp/sup-simcse-bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


# Hyperparameter Optimization

In [9]:
! pip install optuna --quiet

     |████████████████████████████████| 308 kB 9.1 MB/s 
     |████████████████████████████████| 80 kB 10.9 MB/s 
     |████████████████████████████████| 209 kB 72.6 MB/s 
     |████████████████████████████████| 75 kB 5.6 MB/s 
     |████████████████████████████████| 112 kB 66.5 MB/s 
     |████████████████████████████████| 49 kB 7.6 MB/s 
     |████████████████████████████████| 149 kB 75.4 MB/s 


In [10]:
def model_init():
    return AutoModelForSequenceClassification.from_pretrained(modeltype, num_labels=2)

In [11]:
trainer = Trainer(
      model_init=model_init,
      args=training_args, 
      train_dataset=full_train_dataset, 
      eval_dataset=full_eval_dataset,
      compute_metrics=compute_metrics 
  )

loading configuration file https://huggingface.co/princeton-nlp/sup-simcse-bert-base-uncased/resolve/main/config.json from cache at /root/.cache/huggingface/transformers/886dba277a27c6ab50ab3d0bfd8839d354cfeed717289623026415c62b687338.1b14bcddba43d86a607eedb4b638b87d30aa00c839358953dbd36f2cd3317c83
Model config BertConfig {
  "_name_or_path": "princeton-nlp/sup-simcse-bert-base-uncased",
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weights file

In [12]:
import sklearn.metrics as metrics
import optuna
import sys
import logging

def objective (metrics):
  return metrics['eval_f1']

def hyperparameter_space(trial):

    return {
        "learning_rate": trial.suggest_float("learning_rate", 5e-8, 5e-1, log=True),
        "per_device_train_batch_size": trial.suggest_categorical("per_device_train_batch_size", [2, 4, 8, 16]),
        "weight_decay": trial.suggest_float("weight_decay", 5e-12, 5e-1, log=True),
        "num_train_epochs": trial.suggest_float("num_train_epochs",1,8,log=True),
        #"adam_epsilon": trial.suggest_float("adam_epsilon", 1e-10, 1e-6, log=True),
        #"seed" : trial.suggest_float("seed",10,60,log=True)
        }

optuna.logging.get_logger("optuna").addHandler(logging.StreamHandler(sys.stdout))
study_name = "SIMCSE_BERT_myPers_AGR"  # Unique identifier of the study.
storage_name = "sqlite:///{}.db".format(study_name)

best_run = trainer.hyperparameter_search(hp_space=hyperparameter_space,compute_objective=objective, n_trials=8, direction="maximize",study_name=study_name, storage=storage_name,load_if_exists=True )

study = optuna.create_study()

[I 2021-12-25 15:55:40,162] Using an existing study with name 'SIMCSE_BERT_myPers_AGR' instead of creating a new one.


Using an existing study with name 'SIMCSE_BERT_myPers_AGR' instead of creating a new one.


Trial:
loading configuration file https://huggingface.co/princeton-nlp/sup-simcse-bert-base-uncased/resolve/main/config.json from cache at /root/.cache/huggingface/transformers/886dba277a27c6ab50ab3d0bfd8839d354cfeed717289623026415c62b687338.1b14bcddba43d86a607eedb4b638b87d30aa00c839358953dbd36f2cd3317c83
Model config BertConfig {
  "_name_or_path": "princeton-nlp/sup-simcse-bert-base-uncased",
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weigh

The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.53      0.53      0.53       930
           1       0.58      0.58      0.58      1054

    accuracy                           0.56      1984
   macro avg       0.55      0.55      0.55      1984
weighted avg       0.56      0.56      0.56      1984

[[489 441]
 [440 614]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.53      0.55      0.54       930
           1       0.59      0.57      0.58      1054

    accuracy                           0.56      1984
   macro avg       0.56      0.56      0.56      1984
weighted avg       0.56      0.56      0.56      1984

[[515 415]
 [456 598]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.55      0.57      0.56       930
           1       0.61      0.58      0.60      1054

    accuracy                           0.58      1984
   macro avg       0.58      0.58      0.58      1984
weighted avg       0.58      0.58      0.58      1984

[[533 397]
 [438 616]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.57      0.49      0.53       930
           1       0.60      0.67      0.63      1054

    accuracy                           0.59      1984
   macro avg       0.58      0.58      0.58      1984
weighted avg       0.58      0.59      0.58      1984

[[456 474]
 [346 708]]


[I 2021-12-25 16:38:07,879] Trial 44 pruned. 


Trial 44 pruned. 


Trial:
loading configuration file https://huggingface.co/princeton-nlp/sup-simcse-bert-base-uncased/resolve/main/config.json from cache at /root/.cache/huggingface/transformers/886dba277a27c6ab50ab3d0bfd8839d354cfeed717289623026415c62b687338.1b14bcddba43d86a607eedb4b638b87d30aa00c839358953dbd36f2cd3317c83
Model config BertConfig {
  "_name_or_path": "princeton-nlp/sup-simcse-bert-base-uncased",
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weigh

The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.00      0.00      0.00       930
           1       0.53      1.00      0.69      1054

    accuracy                           0.53      1984
   macro avg       0.27      0.50      0.35      1984
weighted avg       0.28      0.53      0.37      1984

[[   0  930]
 [   0 1054]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` param

Trial 45 pruned. 


Trial:
loading configuration file https://huggingface.co/princeton-nlp/sup-simcse-bert-base-uncased/resolve/main/config.json from cache at /root/.cache/huggingface/transformers/886dba277a27c6ab50ab3d0bfd8839d354cfeed717289623026415c62b687338.1b14bcddba43d86a607eedb4b638b87d30aa00c839358953dbd36f2cd3317c83
Model config BertConfig {
  "_name_or_path": "princeton-nlp/sup-simcse-bert-base-uncased",
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weigh

The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.52      0.57      0.54       930
           1       0.59      0.54      0.57      1054

    accuracy                           0.56      1984
   macro avg       0.56      0.56      0.56      1984
weighted avg       0.56      0.56      0.56      1984

[[528 402]
 [480 574]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.54      0.54      0.54       930
           1       0.60      0.60      0.60      1054

    accuracy                           0.57      1984
   macro avg       0.57      0.57      0.57      1984
weighted avg       0.57      0.57      0.57      1984

[[503 427]
 [425 629]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.54      0.62      0.58       930
           1       0.61      0.53      0.57      1054

    accuracy                           0.57      1984
   macro avg       0.57      0.57      0.57      1984
weighted avg       0.58      0.57      0.57      1984

[[575 355]
 [495 559]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.58      0.48      0.52       930
           1       0.60      0.69      0.64      1054

    accuracy                           0.59      1984
   macro avg       0.59      0.59      0.58      1984
weighted avg       0.59      0.59      0.59      1984

[[446 484]
 [324 730]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.57      0.53      0.55       930
           1       0.61      0.65      0.63      1054

    accuracy                           0.59      1984
   macro avg       0.59      0.59      0.59      1984
weighted avg       0.59      0.59      0.59      1984

[[489 441]
 [366 688]]


[I 2021-12-25 17:41:23,335] Trial 46 pruned. 


Trial 46 pruned. 


Trial:
loading configuration file https://huggingface.co/princeton-nlp/sup-simcse-bert-base-uncased/resolve/main/config.json from cache at /root/.cache/huggingface/transformers/886dba277a27c6ab50ab3d0bfd8839d354cfeed717289623026415c62b687338.1b14bcddba43d86a607eedb4b638b87d30aa00c839358953dbd36f2cd3317c83
Model config BertConfig {
  "_name_or_path": "princeton-nlp/sup-simcse-bert-base-uncased",
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weigh

The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.00      0.00      0.00       930
           1       0.53      1.00      0.69      1054

    accuracy                           0.53      1984
   macro avg       0.27      0.50      0.35      1984
weighted avg       0.28      0.53      0.37      1984

[[   0  930]
 [   0 1054]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` param

Trial 47 pruned. 


Trial:
loading configuration file https://huggingface.co/princeton-nlp/sup-simcse-bert-base-uncased/resolve/main/config.json from cache at /root/.cache/huggingface/transformers/886dba277a27c6ab50ab3d0bfd8839d354cfeed717289623026415c62b687338.1b14bcddba43d86a607eedb4b638b87d30aa00c839358953dbd36f2cd3317c83
Model config BertConfig {
  "_name_or_path": "princeton-nlp/sup-simcse-bert-base-uncased",
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weigh

The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.52      0.33      0.40       930
           1       0.55      0.73      0.63      1054

    accuracy                           0.54      1984
   macro avg       0.54      0.53      0.52      1984
weighted avg       0.54      0.54      0.52      1984

[[308 622]
 [286 768]]


[I 2021-12-25 18:01:04,210] Trial 48 pruned. 


Trial 48 pruned. 


Trial:
loading configuration file https://huggingface.co/princeton-nlp/sup-simcse-bert-base-uncased/resolve/main/config.json from cache at /root/.cache/huggingface/transformers/886dba277a27c6ab50ab3d0bfd8839d354cfeed717289623026415c62b687338.1b14bcddba43d86a607eedb4b638b87d30aa00c839358953dbd36f2cd3317c83
Model config BertConfig {
  "_name_or_path": "princeton-nlp/sup-simcse-bert-base-uncased",
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weigh

The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.51      0.65      0.58       930
           1       0.60      0.45      0.52      1054

    accuracy                           0.55      1984
   macro avg       0.56      0.55      0.55      1984
weighted avg       0.56      0.55      0.54      1984

[[609 321]
 [577 477]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.57      0.50      0.53       930
           1       0.60      0.66      0.63      1054

    accuracy                           0.59      1984
   macro avg       0.58      0.58      0.58      1984
weighted avg       0.58      0.59      0.58      1984

[[469 461]
 [359 695]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.57      0.54      0.55       930
           1       0.61      0.64      0.62      1054

    accuracy                           0.59      1984
   macro avg       0.59      0.59      0.59      1984
weighted avg       0.59      0.59      0.59      1984

[[502 428]
 [382 672]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.59      0.43      0.50       930
           1       0.59      0.74      0.66      1054

    accuracy                           0.59      1984
   macro avg       0.59      0.58      0.58      1984
weighted avg       0.59      0.59      0.58      1984

[[398 532]
 [277 777]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.58      0.53      0.56       930
           1       0.62      0.66      0.64      1054

    accuracy                           0.60      1984
   macro avg       0.60      0.60      0.60      1984
weighted avg       0.60      0.60      0.60      1984

[[497 433]
 [356 698]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.59      0.46      0.52       930
           1       0.60      0.72      0.65      1054

    accuracy                           0.60      1984
   macro avg       0.60      0.59      0.59      1984
weighted avg       0.60      0.60      0.59      1984

[[432 498]
 [299 755]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.59      0.50      0.54       930
           1       0.61      0.69      0.65      1054

    accuracy                           0.60      1984
   macro avg       0.60      0.60      0.59      1984
weighted avg       0.60      0.60      0.60      1984

[[469 461]
 [330 724]]


The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.58      0.50      0.54       930
           1       0.61      0.69      0.64      1054

    accuracy                           0.60      1984
   macro avg       0.60      0.59      0.59      1984
weighted avg       0.60      0.60      0.59      1984

[[464 466]
 [332 722]]




Training completed. Do not forget to share your model on huggingface.co/models =)


[I 2021-12-25 19:20:02,575] Trial 49 finished with value: 0.5908635622680047 and parameters: {'learning_rate': 1.2693957149406535e-05, 'per_device_train_batch_size': 2, 'weight_decay': 1.314949008040136e-08, 'num_train_epochs': 7.42519371339904}. Best is trial 12 with value: 0.6002162006600213.


Trial 49 finished with value: 0.5908635622680047 and parameters: {'learning_rate': 1.2693957149406535e-05, 'per_device_train_batch_size': 2, 'weight_decay': 1.314949008040136e-08, 'num_train_epochs': 7.42519371339904}. Best is trial 12 with value: 0.6002162006600213.


Trial:
loading configuration file https://huggingface.co/princeton-nlp/sup-simcse-bert-base-uncased/resolve/main/config.json from cache at /root/.cache/huggingface/transformers/886dba277a27c6ab50ab3d0bfd8839d354cfeed717289623026415c62b687338.1b14bcddba43d86a607eedb4b638b87d30aa00c839358953dbd36f2cd3317c83
Model config BertConfig {
  "_name_or_path": "princeton-nlp/sup-simcse-bert-base-uncased",
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weigh

The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.51      0.28      0.36       930
           1       0.55      0.76      0.64      1054

    accuracy                           0.54      1984
   macro avg       0.53      0.52      0.50      1984
weighted avg       0.53      0.54      0.51      1984

[[263 667]
 [250 804]]


[I 2021-12-25 19:30:38,986] Trial 50 pruned. 


Trial 50 pruned. 


Trial:
loading configuration file https://huggingface.co/princeton-nlp/sup-simcse-bert-base-uncased/resolve/main/config.json from cache at /root/.cache/huggingface/transformers/886dba277a27c6ab50ab3d0bfd8839d354cfeed717289623026415c62b687338.1b14bcddba43d86a607eedb4b638b87d30aa00c839358953dbd36f2cd3317c83
Model config BertConfig {
  "_name_or_path": "princeton-nlp/sup-simcse-bert-base-uncased",
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weigh

The following columns in the evaluation set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: __index_level_0__, text.
***** Running Evaluation *****
  Num examples = 1984
  Batch size = 8


              precision    recall  f1-score   support

           0       0.00      0.00      0.00       930
           1       0.53      1.00      0.69      1054

    accuracy                           0.53      1984
   macro avg       0.27      0.50      0.35      1984
weighted avg       0.28      0.53      0.37      1984

[[   0  930]
 [   0 1054]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` param

Trial 51 pruned. 


[I 2021-12-25 19:41:16,909] A new study created in memory with name: no-name-4e3d942c-7d72-427d-9ab1-b4c95500d597


A new study created in memory with name: no-name-4e3d942c-7d72-427d-9ab1-b4c95500d597


In [13]:
storage_name

'sqlite:///SIMCSE_BERT_myPers_AGR.db'

In [14]:
study_name

'SIMCSE_BERT_myPers_AGR'

In [15]:
study = optuna.create_study(study_name=study_name, storage=storage_name, load_if_exists=True, direction="maximize")
df = study.trials_dataframe(attrs=("number", "value", "params", "state"))

[I 2021-12-25 19:41:17,004] Using an existing study with name 'SIMCSE_BERT_myPers_AGR' instead of creating a new one.


Using an existing study with name 'SIMCSE_BERT_myPers_AGR' instead of creating a new one.


In [16]:
df

number     value  ...  params_weight_decay     state
0        0  0.493657  ...         1.274813e-09  COMPLETE
1        1  0.319149  ...         9.147818e-02  COMPLETE
2        2  0.346939  ...         5.831691e-04  COMPLETE
3        3  0.459720  ...         6.342396e-11  COMPLETE
4        4  0.346939  ...         2.079299e-11  COMPLETE
5        5  0.346939  ...         6.557118e-02  COMPLETE
6        6  0.570077  ...         1.716952e-03  COMPLETE
7        7  0.319149  ...         3.289601e-11    PRUNED
8        8  0.346939  ...         8.964743e-11  COMPLETE
9        9  0.346939  ...         4.178087e-04    PRUNED
10      10  0.576265  ...         2.444671e-07  COMPLETE
11      11  0.593389  ...         1.148860e-07  COMPLETE
12      12  0.600216  ...         1.320825e-07  COMPLETE
13      13  0.574914  ...         1.706779e-07    PRUNED
14      14  0.449059  ...         1.107825e-08    PRUNED
15      15  0.346939  ...         1.246026e-05    PRUNED
16      16  0.587946  ...         3.672365e-06  COMPLETE
17      17  0.449059  ...         7.093289e-09    PRUNED
18      18  0.592105  ...         2.733663e-05  COMPLETE
19      19  0.458665  ...         2.263869e-07    PRUNED
20      20  0.346939  ...         9.487481e-10    PRUNED
21      21  0.586085  ...         3.242506e-05  COMPLETE
22      22  0.575585  ...         4.969250e-07    PRUNED
23      23  0.544345  ...         7.414304e-05    PRUNED
24      24  0.346939  ...         2.949572e-08    PRUNED
25      25  0.346939  ...         2.737094e-06    PRUNED
26      26  0.346939  ...         8.095201e-03    PRUNED
27      27  0.506700  ...         7.252672e-08    PRUNED
28      28  0.455932  ...         1.390274e-09    PRUNED
29      29  0.462406  ...         1.891641e-06    PRUNED
30      30  0.557851  ...         1.483345e-04    PRUNED
31      31  0.574045  ...         3.304925e-06    PRUNED
32      32  0.586995  ...         1.416899e-05    PRUNED
33      33  0.346939  ...         7.126142e-07    PRUNED
34      34  0.438979  ...         3.549096e-09    PRUNED
35      35  0.485280  ...         7.228970e-06    PRUNED
36      36  0.346939  ...         4.582966e-08    PRUNED
37      37  0.574869  ...         4.150193e-01    PRUNED
38      38  0.501378  ...         4.569275e-03    PRUNED
39      39  0.346939  ...         3.725681e-10    PRUNED
40      40  0.346939  ...         9.808942e-07    PRUNED
41      41  0.592966  ...         7.166677e-05  COMPLETE
42      42  0.591662  ...         2.916087e-04    PRUNED
43      43       NaN  ...         5.129059e-05   RUNNING
44      44  0.579916  ...         4.540382e-05    PRUNED
45      45  0.346939  ...         7.648543e-04    PRUNED
46      46  0.589112  ...         6.119778e-06    PRUNED
47      47  0.346939  ...         1.670164e-05    PRUNED
48      48  0.516339  ...         1.169589e-07    PRUNED
49      49  0.590864  ...         1.314949e-08  COMPLETE
50      50  0.500675  ...         1.333819e-08    PRUNED
51      51  0.346939  ...         2.035906e-10    PRUNED

[52 rows x 7 columns]

In [17]:
fig = optuna.visualization.plot_param_importances(study)
fig.show()

In [18]:
best_run

BestRun(run_id='12', objective=0.6002162006600213, hyperparameters={'learning_rate': 1.1303968708302916e-05, 'num_train_epochs': 7.7171833770773, 'per_device_train_batch_size': 2, 'weight_decay': 1.3208253773473318e-07})

In [19]:
optuna.visualization.plot_intermediate_values(study)

In [20]:
optuna.visualization.plot_parallel_coordinate(study)

In [21]:
optuna.visualization.plot_optimization_history(study)

In [22]:
optuna.visualization.plot_contour(study)

In [23]:
optuna.visualization.plot_slice(study)

In [24]:
optuna.visualization.plot_edf(study)